Specify sqlite3 version in Gemfile
I was getting:

  LoadError: Please install the sqlite3 adapter: `gem install activerecord-sqlite3-adapter` (can't activate sqlite3 (~> 1.3.5), already activated sqlite3-1.4.2. Make sure all dependencies are added to Gemfile.)